config/routes.rb
AtWork::Application.routes.draw do
  resources :users
  resources :users do
    resources :accomplishments
  end
  match '/login/create' => 'login#create', as: :login
  match '/login' => 'login#new', as: :login
  match '/logout' => 'login#destroy', as: :logout
  match '/' => 'application#index'
  match '/refresh_everyone' => 'application#refresh_everyone'
  match '/refresh_timeline' => 'application#refresh_timeline'
end

app/models/accomplishment.rb
class Accomplishment < ActiveRecord::Base
  validates_presence_of :accomplishment, on: :create, message: "can't be blank"
  belongs_to :user
  attr_accessible :accomplishment, :user

  def self.recent_accomplishments
    where("user_id IS NOT NULL AND created_at > :created_at", created_at: 9.days.ago).order("created_at DESC").all
  end
end

app/controllers/accomplishments_controller.rb
class AccomplishmentsController < ApplicationController
  before_filter :login_required
  before_filter :admin_required, only: [:index, :show, :new, :edit, :update, :destroy]
  # GET /accomplishments
  # GET /accomplishments.json
  def index
    @accomplishments = Accomplishment.where("user_id = :user_id", user_id: params[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accomplishments }
    end
  end

  # GET /accomplishments/1
  # GET /accomplishments/1.json
  def show
    @accomplishment = Accomplishment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @accomplishment }
    end
  end

  # GET /accomplishments/new
  # GET /accomplishments/new.json
  def new
    @accomplishment = Accomplishment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @accomplishment }
    end
  end

  # GET /accomplishments/1/edit
  def edit
    @accomplishment = Accomplishment.find(params[:id])
  end

  # POST /accomplishments
  # POST /accomplishments.json
  def create
    @accomplishment = Accomplishment.new(params[:accomplishment])
    @accomplishment.user = current_user

    @user = current_user
    @user.accomplishments.create(accomplishment: params[:add_accomplishment])
    @users = User.active_users
    @recent_activity = Accomplishment.recent_accomplishments

    respond_to do |format|
      if @accomplishment.save
        @recent_activity = Accomplishment.recent_accomplishments
        format.html { redirect_to user_accomplishment_url(current_user, @accomplishment), notice: 'Accomplishment was successfully created.' }
        format.js { render status: :created }
        format.json { render json: @accomplishment, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @accomplishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accomplishments/1
  # PUT /accomplishments/1.json
  def update
    @accomplishment = Accomplishment.find(params[:id])

    respond_to do |format|
      if @accomplishment.update_attributes(params[:accomplishment])
        format.html { redirect_to @accomplishment, notice: 'Accomplishment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @accomplishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accomplishments/1
  # DELETE /accomplishments/1.json
  def destroy
    @accomplishment = Accomplishment.find(params[:id])
    @accomplishment.destroy

    respond_to do |format|
      format.html { redirect_to accomplishments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accomplishments_helper.rb
module AccomplishmentsHelper
end

app/views/accomplishments/_form.html.erb
<%= form_for(@accomplishment) do |f| %>
  <% if @accomplishment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accomplishment.errors.count, "error") %> prohibited this accomplishment from being saved:</h2>

      <ul>
      <% @accomplishment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accomplishments/create.js.erb
$("#timeline").html('<%= escape_javascript(render("application/timeline")) %>');
$("#everyone").html('<%= escape_javascript(render("application/everyone")) %>');

app/views/accomplishments/edit.html.erb
<h1>Editing accomplishment</h1>

<%= render 'form' %>

<%= link_to 'Show', @accomplishment %> |
<%= link_to 'Back', accomplishments_path %>

app/views/accomplishments/index.html.erb
<h1>Listing accomplishments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accomplishments.each do |accomplishment| %>
  <tr>
    <td><%= link_to 'Show', accomplishment %></td>
    <td><%= link_to 'Edit', edit_accomplishment_path(accomplishment) %></td>
    <td><%= link_to 'Destroy', accomplishment, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Accomplishment', new_accomplishment_path %>

app/views/accomplishments/new.html.erb
<h1>New accomplishment</h1>

<%= render 'form' %>

<%= link_to 'Back', accomplishments_path %>

app/views/accomplishments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_accomplishment_url(current_user, @accomplishment) %> |
<%= link_to 'Back', user_accomplishments_url(current_user) %>