config/routes.rb
AtWork::Application.routes.draw do
  resources :users
  resources :users do
    resources :accomplishments
  end
  match '/login/create' => 'login#create', as: :login
  match '/login' => 'login#new', as: :login
  match '/logout' => 'login#destroy', as: :logout
  match '/' => 'application#index'
  match '/refresh_everyone' => 'application#refresh_everyone'
  match '/refresh_timeline' => 'application#refresh_timeline'
end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base
  ADMIN_EMAIL = "admin@"
  has_many :accomplishments
  # Virtual attribute for the unencrypted password
  attr_accessor :password

  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :password, if: :password_required?
  validates_presence_of :password_confirmation, if: :password_required?
  validates_length_of :password, within: 4..40, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validates_length_of :email, within: 3..100
  validates_uniqueness_of :email, case_sensitive: false
  before_save :encrypt_password

  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :current_status

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  def self.authenticate(login, password)
    u = find_by_email(login) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  # Encrypts some data with the salt.
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  def self.active_users
    where("current_status is not null").order("first_name").all
  end

  def admin?
    email == AtWork::ADMIN_EMAIL
  end

  # Encrypts the password with the user salt
  def encrypt(password)
    self.class.encrypt(password, salt)
  end

  def authenticated?(password)
    crypted_password == encrypt(password)
  end

  def remember_token?
    remember_token_expires_at && Time.now.utc < remember_token_expires_at
  end

  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    remember_me_for 2.weeks
  end

  def remember_me_for(time)
    remember_me_until time.from_now.utc
  end

  def remember_me_until(time)
    self.remember_token_expires_at = time
    self.remember_token = encrypt("#{email}--#{remember_token_expires_at}")
    save
  end

  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token = nil
    save
  end

  # Returns true if the user has just been activated.
  def recently_activated?
    @activated
  end

  protected

  # before filter
  def encrypt_password
    return if password.blank?
    self.salt = Digest::SHA1.hexdigest("--#{Time.now}--#{email}--") if new_record?
    self.crypted_password = encrypt(password)
  end

  def password_required?
    crypted_password.blank? || !password.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required
  before_filter :admin_required, only: [:index, :show, :new, :edit, :create, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = current_user
    @user.accomplishments.create(accomplishment: "Changed Status: #{params[:user][:current_status]}")
    @users = User.active_users
    @recent_activity = Accomplishment.recent_accomplishments

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.json { render json: @user }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :first_name %>
  <p><%= f.text_field :first_name %></p>
  <%= f.label :last_name %>
  <p><%= f.text_field :last_name %></p>
  <%= f.label :email %>
  <p><%= f.text_field :email %></p>
  <%= f.label :password %>
  <p><%= f.password_field :password %></p>
  <%= f.label :password_confirmation %>
  <p><%= f.password_field :password_confirmation %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.email, user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>